import AboutContent from "@/Components/AboutContent/AboutContent";
import React from "react";

export const metadata = {
  title: "About",
  description: "Generated by create next app",
  keywords: ["about", "about page"],
};

const aboutPage = () => {
  return (
    <div>
      <h2>This is about</h2>
      <AboutContent />
    </div>
  );
};

export default aboutPage;
