import { Inter } from "next/font/google";
import { Roboto } from "next/font/google";
import "./globals.css";
import NavBar from "@/Components/NavBar/page";

const inter = Inter({ subsets: ["latin"] });
const roboto = Roboto({ weight: ["400", "500", "700"], subsets: ["latin"] });

export const metadata = {
  title: {
    default: "Next Hero",
    template: "%s|Next Hero",
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="bg-red-500 py-5 text-white">
          <NavBar></NavBar>
        </div>
        <div className="min-h-screen">{children}</div>
        <div className="bg-red-500">
          <h2 className="text-center">Footer</h2>
        </div>
      </body>
    </html>
  );
}
